### ISSUE TITLE
can't adapt type 'ULID' / invalid input syntax for type uuid

### ISSUE THREAD

**Issue by opentyler** [ahawker/django-ulid#61]
Hey first of all thanks for all the great work putting this together eh, both the python ulid package itself and django_ulid.

I've run into an issue where when I run a query like: 

'UPDATE "documents_document" SET numchild=numchild+1 WHERE path='0001' AND tree_root_pk='01EMF1XKJB3G1BXPKFC6MA7B04'

I get an error like: "can't adapt type 'ULID'""

I realized that this is because I need to str() the ULID id, otherwise I kept getting the ULID class object in my queries

But once I ensured the ULID is a string, I get the error: 

Error: invalid input syntax for type uuid: "01EMF1XKJB3G1BXPKFC6MA7B04"
LINE 1: ...ild=numchild+1 WHERE path='0001' AND tree_root_pk='01EMF1XKJ...

From what I understand, this is simply the field failing postgres's uuid type checking (e.g. it's too short of a string). When I try everything the same, but with uuid-compatible string instead of ulid string, everything works because it passes the uuid typecheck

Now of course postgres doesn't have ulid type checking (tho apparently something similar is being proposed). 

So I believe best bet is to forcefully cast the postgres field to ::text, but when I try that I get: 

Error: operator does not exist: uuid = text
LINE 1: ...hild=numchild+1 WHERE path='0001' AND tree_root_pk='01EMF1XK...

So I'm not quite sure how to bypass postgres' uuid field checks on the django_ulid field. Is anyone else running into this issue? 

Full Traceback: 
Environment:

Request Method: POST
Request URL: http://127.0.0.1:8000/document/01EMF1XKJB3G1BXPKFC6MA7B04/

Django Version: 3.0.5
Python Version: 3.7.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.postgres.fields',
 'django.contrib.humanize',
 'users',
 'documents.apps.DocumentsConfig',
 'crispy_forms',
 'treebeard',
 'djstripe',
 'froala_editor',
 'debug_toolbar',
 'django_extensions']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'users.middleware.CustomSubscriptionPaymentMiddleware',
 'debug_toolbar.middleware.DebugToolbarMiddleware']

Traceback (most recent call last):
  File "/home/.virtualenvs/km_dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)

The above exception (can't adapt type 'ULID') was the direct cause of the following exception:
  File "/home/.virtualenvs/km_dev/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/.virtualenvs/km_dev/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/.virtualenvs/km_dev/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/.virtualenvs/km_dev/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/.virtualenvs/km_dev/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/project/documents/views.py", line 1098, in post
    comment = comment_form.make_new_document_object()
  File "/project/documents/forms.py", line 151, in make_new_document_object
    new_object = self.target_object.add_child_plus_count(**data)
  File "/project/documents/models.py", line 202, in add_child_plus_count
    return self.add_child(**kwargs)
  File "/project/documents/mp_tree.py", line 1031, in add_child
    return MP_AddChildHandler(self, **kwargs).process()
  File "/project/documents/mp_tree.py", line 373, in process
    'sorted-sibling', **self.kwargs)
  File "/project/documents/mp_tree.py", line 1043, in add_sibling
    return MP_AddSiblingHandler(self, pos, **kwargs).process()
  File "/project/documents/mp_tree.py", line 464, in process
    self.run_sql_stmts()
  File "/project/documents/mp_tree.py", line 149, in run_sql_stmts
    cursor.execute(sql, vals)
  File "/home/.virtualenvs/km_dev/lib/python3.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 198, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/home/.virtualenvs/km_dev/lib/python3.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 133, in _record
    return method(sql, params)
  File "/home/.virtualenvs/km_dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/.virtualenvs/km_dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/.virtualenvs/km_dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/.virtualenvs/km_dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/.virtualenvs/km_dev/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/.virtualenvs/km_dev/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /document/01EMF1XKJB3G1BXPKFC6MA7B04/
Exception Value: can't adapt type 'ULID'

**Comment by ahawker** [comment]
Would it be possible to paste your model definitions or values you're using in `comment_form.make_new_document_object()`? I'm struggling to figure it out from the stack trace here.

The field should convert itself to a UUID ([code here](https://github.com/ahawker/django-ulid/issues/61)) since you're using postgres, which has a native UUID type.

> But once I ensured the ULID is a string, I get the error:
> Error: invalid input syntax for type uuid: "01EMF1XKJB3G1BXPKFC6MA7B04"
> LINE 1: ...ild=numchild+1 WHERE path='0001' AND tree_root_pk='01EMF1XKJ...

Calling `str` on a ULID instance will give you the 26 char, based32 encoded value. Perhaps instead of that, you can try the `.uuid` property, which will give you a valid UUID instance.

```python
>>> import ulid
>>> u = ulid.new()
>>> str(u)
'01EMFEDZRWBVM7WWNE8CQQVD8C'
>>> u.uuid
UUID('01751ee6-ff1c-5ee8-7e72-ae432f7db50c')
```

**Comment by opentyler** [comment]
Hey thanks for responding so quickly! Absolutely I can provide the model definitions and values in comment_form.make_new_document_object().

For the model: 
```
class Document(MP_Node):
    id = ULIDField(default=default, primary_key=True, editable=False)
    tree_root_pk = ULIDField(null=True, blank=True)
    type = models.CharField(max_length=2, choices=DocumentType.choices)

    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, related_name='user_%(class)ss')
    author_name = models.CharField(max_length=255, blank=True, default="")

    title = models.CharField(max_length=10000, blank=True, default="")
    content = models.TextField(max_length=25000, blank=True, default="")
    tags = models.ManyToManyField(Tag, blank=True, related_name='%(class)s', help_text='Enter tags separated by commas')
```

I'm using django-treebeard, hence the inheriting of MP_Node for materialized path trees. Basically every document has ulid as its primary key, but I also use a tree_root_pk ulid field to manage which tree pk the materialized path belongs to. 

For the values in comment_form.make_new_document_object(): 
```
class DocumentDetailForm(DocumentSecurityForm):
    author_name = forms.CharField(max_length=255)
    content = forms.CharField(widget=FroalaEditor)

    def make_new_document_object(self):
        """
        Return a new (unsaved) document object based on the information in this
        form. Assumes that the form is already validated and will throw a
        ValueError if not.
        Does not set any of the fields that would come from a Request object
        (i.e. ``user`` or ``ip_address``).
        """

        if not self.is_valid():
            raise ValueError("make_new_document_object may only be called on valid forms")

        data = self.get_document_create_data()
        data = self.check_for_duplicate_document(**data)

        if data == "duplicate":
            return data
        else:
            new_object = self.target_object.add_child_plus_count(**data) # Treebeard Materialized Path method for creating child node, slightly tweaked
            return new_object

    def get_document_create_data(self):
        """
        Returns the dict of data to be used to create a document.
        """
        return dict(
            tree_root_pk=self.target_object.tree_root_pk,
            author=User.objects.get(username=self.cleaned_data["author_name"]),
            content=self.cleaned_data["content"],
            is_public=True,
        )

```

Your answer provides a lot of clarification though, thank you. I didn't realize that ulid is actually being stored as uuid. That pretty much solves it actually. I used your advice and went with .uuid to get the ulid to simply generate the paired uuid and used that to query and it works beautifully as expected. Makes a lot of sense now. Thank you very very much for your very speedy and helpful reply eh, and thanks again for this library! I'll definitely try to keep my eyes open for any legitiamte bugs and try to do more helpful, substantive documenting of them if I can in future.

**Comment by ahawker** [comment]
@opentyler I'm glad my comment helped. I'll make a note to add some more information to the docs about how the values are stored in the DB. Closing this issue but feel free to re-open if you run into more issues related to this specific problem.
